name: flutter_midi_command_web
description: FlutterMidiCommand for the web.
version: 0.0.1
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterMidiCommandWeb
        fileName: flutter_midi_command_web.dart

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  typings: ^0.0.6+1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_midi_command_platform_interface: ^0.4.1
